# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- deploy/azure-devops-setup

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'IW4MAdmin.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Prerelease'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    msbuildArgs: '/p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      **/WebfrontCore.csproj
      **/Application.csproj
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)\Publish\$(buildConfiguration)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'wget https://raidmax.org/downloads/dos2unix.exe'
    failOnStderr: true
    workingDirectory: '$(Build.Repository.LocalPath)\Application\BuildScripts'
    
- task: BatchScript@1
  inputs:
    filename: 'Application\BuildScripts\PostPublish.bat'
    workingFolder: '$(Build.Repository.LocalPath)'
    arguments: '$(Build.ArtifactStagingDirectory)\Publish\$(buildConfiguration)'
    failOnStandardError: true

- task: PowerShell@2
  inputs:
    filePath: 'PostPublish.ps1'
    arguments: '$(Build.ArtifactStagingDirectory)\Publish\$(buildConfiguration)'
    failOnStderr: true
    workingDirectory: '$(Build.Repository.LocalPath)'
    
- task: CmdLine@2
  inputs:
    script: |
      echo changing to encoding for linux start script
      dos2unix $(Build.ArtifactStagingDirectory)\Publish\$(buildConfiguration)\StartIW4MAdmin.sh
    workingDirectory: '$(Build.Repository.LocalPath)\Application\BuildScripts'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\Publish\$(buildConfiguration)'
    artifact: 'IW4MAdmin.$(buildConfiguration)'
    publishLocation: 'pipeline'

